### ISSUE TITLE
Autocomplete List Stays Open When Switching Tabs

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#1087]
1.  Open 2-3 tabs
2.  Enter a partial URL so autocomplete list shows
3.  Select a different tab using CONTROL+TAB

The Autocomplete list stays open.  Maybe we just close it, or only show it when the user navigates back to that tab?

**Comment by victorporof** [comment]
I can't reproduce this with the steps described, but these do:

1. Open 2-3 tabs
2. Select first tab, enter a partial URL so autocomplete list shows
3. Select a different tab using CONTROL+TAB
4. Enter a partial URL so autocomplete list shows again
5. Select a first tab using CONTROL+TAB

The autocomplete list is open and shows the new results instead of the old ones, even though the text in the location bar is the old one.

Expected: either the autocomplete list isn't open anymore, or it's open but shows the old results.
