### ISSUE TITLE
Make restoring a broken session more resilient to errors made during development

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1474]
I have a session.json file that breaks anytime it's loaded in a packaged build, resulting in:
<img width="1168" alt="screen shot 2016-10-25 at 10 18 46 am" src="https://cloud.githubusercontent.com/assets/641267/19696662/fcb7d2c2-9a9c-11e6-8635-8095a60ab13a.png">

<img width="809" alt="screen shot 2016-10-25 at 10 19 28 am" src="https://cloud.githubusercontent.com/assets/641267/19696575/8971766a-9a9c-11e6-8e81-e2b3cce7949e.png">

Deleting the session.json file fixes the issue. Can provide the file if needed, but it looks like it's missing a lot info (all pages have empty strings as most values), so looks like somewhere in the saving process, it lost data, and attempting to load this again fails resulting in the broken URL bars/tabs in the picture.

**Comment by jsantell** [comment]
Not sure if this is a "real bug" that can occur from non-developers mucking about with sessions and dev builds, but regardless, we should gracefully handle invalid profiles (like require that pages have atleast URLs and what not)

**Comment by victorporof** [comment]
Do you know exactly how you ended up in this state? What did you much about with? This might legitimately be a thing we should be wary of.

**Comment by victorporof** [comment]
Providing the broken session.json file would indeed help.

**Comment by victorporof** [comment]
I've played with the session.json you have me and managed to make our model/reducers/sagas a bit more reliable to get the browser to a usable state. In doing so, it became clear that this happens when a coding error is made in the reducers during development (see attached screenshot).

<img width="832" alt="screen shot 2016-10-26 at 1 12 20 pm" src="https://cloud.githubusercontent.com/assets/248899/19724033/645e31be-9b7e-11e6-83af-25f3a207cab6.png">

Since `location` wasn't converted to an immutable object, the app state wasn't compatible with the view components anymore, and the house of cards collapsed.

I'll try to make restoring a broken session a bit more resilient to such errors, but ultimately I'm not sure how much we can guard against saving bad state after reloading ulterior to an incremental build. Maybe have a flag to disable session save/restore during development.

**Comment by victorporof** [comment]
Not sure if this should be a P1, feel free to change if you disagree.

**Comment by jsantell** [comment]
I think it should be P1, it makes the browser absolutely unusable

**Comment by jsantell** [comment]
That being said, the big issue is nothing works, I can't close tabs, navigate, etc., I'd rather throw out the session.json file and start from scratch
