### ISSUE TITLE
Add `endSession` and `undoEndSession` to storage

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#328]
We definitely need `endSession`; it's just not there yet.

I'd like to do something concrete and distinct for "undoing" a close tab action, too.

@rnewman, can you drive this?

**Comment by rnewman** [comment]
We have `sessionEnds` in the schema, so that should be a simple API addition.

Undoing a tab close: I had imagined a 'reason' column for session starts, so undoing a tab close would be the start of a new session with ancestor = the closed session (already supported), and with reason = reopen. What do you think of that?

**Comment by rnewman** [comment]
And yes, I can drive this.

**Comment by ncalexan** [comment]
@rnewman re: 'reason' column, that's a fine approach.  Session restore, undo, closing tabs because the window closed -- those are all interesting events.

**Comment by rnewman** [comment]
dd3ed2e
