### ISSUE TITLE
Suggestions should be clickable and hoverable

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#642]
<img width="549" alt="screen shot 2016-06-07 at 2 47 54 pm" src="https://cloud.githubusercontent.com/assets/641267/15875905/2d5759a8-2cbf-11e6-8436-f48cd494fa11.png">

As they are now, they react to neither and I'd expect them to be clickable, and also be highlighted in unison with the title

**Comment by bgrins** [comment]
It'd be nice to have some mockup for these autocomplete suggestions.  Do we event want to show the page content directly inline in the autocomplete popup?  If so, what should it look like?  @phlsa, any guidance?

**Comment by phlsa** [comment]
Hm, how do I get to the state in Jordans screen shot? I have to admit that I haven't really been using Tofino up until we started with builds...

**Comment by bgrins** [comment]
You might need to do hamburger -> fetch page contents to get it to work (don't think we are automatically saving content)

**Comment by bgrins** [comment]
to be clear, the URL and page title are clickable / hoverable, it's the additional content (readability version of the page) that is tacked on.   A text match could have happened in that content but not the url/title, which is why it's currently visible.  We could always hide that content for now, but if you had ideas of what a richer autocomplete suggestion would look like that would be helpful (i.e. more than just page title / url / favicon)

**Comment by phlsa** [comment]
Per #740, let's hide the full text by default. A slightly longer explanation is in that issue :)

**Comment by victorporof** [comment]
Fixed by the frontend rewrite.
