### ISSUE TITLE
Add DataScript schema, schema version, and migration path to persistence layer

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#752]
The work at #746 needs to grow to include a KB (Knowledge Base) schema in the persistent DB store, so that we can migrate that forward as the KB data model changes.

**Comment by ncalexan** [comment]
I started thinking about this more seriously.  There is some prior art from the Datomic community.  The two most interesting that I found are:

* https://github.com/rkneufeld/conformity handles atomic schema updates.  It doesn't handle data migrations.
* https://github.com/bitemyapp/brambling explicitly handles data migrations.  It replays the transaction log, maps and filters it, and applies the transformed transactions against a new database.

Both are quite closely tied to Datomic; they'd need pretty significant effort to work with DataScript and our hacked together SQLite transaction log.  However, they both suggest APIs and implementations for their functionality.

I think a combination of these two things will service our needs for the UA Service.  However, we have a harder problem that we'd like to at least define, if not address.  We want independent UI implementations to be able to use the same underlying store for UI experiments, and I think that means that each UI experiment will want to be able to update the underlying UA Service schema for its needs.  However, we shouldn't assume that our UI experiments are co-ordinated.  We might declare that each UI experiment is weakly namespaced to separate schema changes; and then have a migration into the core UA Service schema as experiments prove useful.  But even then, we still need to push schema changes to the edges of the experiment space so that they can be rapidly developed before being accepted into the core UA Service schema.

The Datomic model for schema updates is that peer asserts its desired schema values at connection time.  (Conformity exposes `ensure-conforms` to assert this.)  Underlying this is the fact that Datomic reifies its schema into the store and processes changes to the `:db` part, atomically, as they arrive.  DataScript doesn't reify it's schema, doesn't have explicit parts, and isn't built to update it's schema (and hence indexes!) on the fly.  There's non-trivial work to support that.

Since our UI experiments are *not* Datomic peers, but instead consumers of the central UA Service, we could instead add a special `/schema` endpoint to support some subset of that work.  A UI experiment that needed some schema attributes in particular could ask for them at connection time.  The UA Service would still have to do much the same work, but could do it based on special SQLite tables rather than in the DS store, etc.

**Comment by rnewman** [comment]
I think it's worth teasing apart the problem here.

Schema changes can involve:

- Changes to an existing attribute: e.g., changing cardinality. This might involve migrating data.
- Replacing an attribute altogether (e.g., to reify or un-reify a domain concept). This does involve migrating data, losing data, or transparently remapping data at query time.
- Adding a new attribute. This (ordinarily?) does not involve migrating data.

If we limit our consumers to adding properties (which includes weak/on-the-fly replacement), then we essentially ignore all of the hard parts of schema evolution.

I don't think that doing so allows us to avoid migration and schema management in the long run. But it means that a short-term solution based on unioning and persisting unchanging, stably identified schema fragments is perhaps adequate for now.

**Comment by rnewman** [comment]
This has been shifted into Datomish.
