### ISSUE TITLE
Webview forward navigation doesn't always work

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#996]
STR:

Open https://duckduckgo.com/?q=test
Click on a result and let the page load
Press back
Press forward

Expected:
You end up on the result page

Actual:
Pressing forward doesn't do anything

**Comment by bgrins** [comment]
This is getting through the webViewController alright and this call to webview.goForward() is happening: https://github.com/mozilla/tofino/blob/5a7444f6a034395dfca5f0da40a117c2c453d369/app/ui/browser/views/page/index.jsx#L67

**Comment by darkwing** [comment]
Not sure if it's the same issue but CMD+LEFTARROW doesn't work for me at all, nor does CMD+RIGHTARROW

**Comment by bgrins** [comment]
> Not sure if it's the same issue but CMD+LEFTARROW doesn't work for me at all, nor does CMD+RIGHTARROW

Have a fix for that in #995

**Comment by Mossop** [comment]
This appears to be broken in electron itself and brave is affected too. I'll take it.

**Comment by victorporof** [comment]
AFAIK there's no way to access history for an electron's webview (as an array of urls for example). So we're going to have to keep a list of page histories in our app state anyway to fix https://github.com/mozilla/tofino/issues/1101, https://github.com/mozilla/tofino/issues/1102, https://github.com/mozilla/tofino/issues/1011 and https://github.com/mozilla/tofino/issues/1017 anyway.

If we do that, we might as well stop relying on webview's `goForward` and just perform a normal `setAttribute(src)` where src would be the url next in that page's history, from our app state. We don't have any support for bfcache at the moment at all, so this won't regress anything.

It's a simple workaround instead of a fix.

**Comment by Mossop** [comment]
It's extremely complicated to keep track of history, that is why this bug happens, because electron are attempting to do it themselves instead of relying on the history implementation in chromium and getting themselves out of sync. Plus reloading instead of using back/forward means we lose all the bfcache behaviours which would make history navigations faster.

I'm more inclined to hack on electron and give us a way to bypass electron's broken history implementation and give us a way to access chromium's.

**Comment by victorporof** [comment]
I agree. I tried implementing something that keeps track of history based on the webview navigation events, and it's indeed extremely difficult to properly handle everything right.

I filed https://github.com/electron/electron/issues/7186 for getting access to history instead of doing this ourselves.

**Comment by Mossop** [comment]
This is fixed upstream by https://github.com/electron/electron/pull/7175

**Comment by victorporof** [comment]
@Mossop does that break our accessing `history`?

**Comment by Mossop** [comment]
@victorporof nope

**Comment by jack008** [comment]
I am up with the question in version 1.4.13.It's not working at all
